---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          # Prevent reporting of e.g. validation blocks as duplication warnings;
          # a certain degree of duplication is acceptable in the name of
          # readability.
          mass_threshold: 25
        javascript:
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.module"
exclude_paths:
- spec/
- vendor/
