language: ruby
cache: bundler

addons:
  postgresql: "9.4"

# We need nodejs version >= 4 to be compatible with htmlhint >= 0.9.13
# This overwrites the system node  0.10.x
before_install:
  - nvm install node

rvm:
  - 2.3.1

bundler_args: --binstubs=./bundler_stubs

before_script:
  - npm install -g jshint coffeelint htmlhint csslint # overcommit packages
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake --trace before_commit:run_without_checks

script:
  - htmlhint -c ./.htmlhintrc ./app/**/*.html.erb
  - git config --global user.email test@example.com # overcommit Author
  - git config --global user.name "Test Example" # overcommit Author
  - BUNDLE_GEMFILE=.overcommit_gems.rb bundle exec overcommit --run
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec "rspec --format progress spec"

# This section was added as per https://docs.travis-ci.com/user/code-climate/
# To protect our codeclimate stats rather than adding the Codeclimate API key for this project
# in the open we used this guide https://docs.travis-ci.com/user/encryption-keys/ to encryt the
# value. Essentially install travis gem, then run `travis encrypt <my_code_climate_api_key>`
addons:
  code_climate:
    repo_token:
      secure: "MVx6bPhKifyvRcQq2V9YdQ1xy/mBGwrya7DKsQl1p/wtfUacB3OrO5gukJm0JCuU+x5eD8gWt/vAr1+DDGA6d0d4G6lkSTZ7cHoczMyRUXjGPRNhUyjNn3eLLVjUtfBNaKAKW/FZfBp+vqY8vnetG5CWcG9y+6jBWznvqk3lfQYtToZp4GPJiBrqLuhSxQYgTCk+j9IUxVV50pQM0jL9aGpeqKFE7poGz+4NqeGhYHsf+JmclFbCVjPljnA22cujb2zEl8OIR7+Xe6who3ddQYCBGy/qZQ8ASJHFIkc3cjN0cm9o7fsROjn9X5R5TOtlzp0EL5gbe1MUdWxe0a3fQVmL4ibm9v/k1OhqgWV9QaJfC1xdJeoct4R1gFtEFE3ZX0e4yDQn2DqVId80oDH8vGh2NRYhhUMfK1etgkMoqElHnoYdTTfu5c+4U0p8f9zWWAtlooqZaJhGOf59rgkzQ12huCswgWW9LcDxX4hEBHMjfc/mX6muWaKSlmcAeDkEVvk10e6mIW6ErUDtAyrntWWEp4PPnRrPmiNE+vQLyCtaGnzmguSqwOHwxanqnhvSZm6kNXAvBOOxvZPl5fMeDpPNbUO07uJ5bp+uN4Hzj+/5rpqX3idfqbO6Vw/J+OEjU9aso1aa+Av+Mp+KFmnEGANYmV9bT/HBl7r50zqXIgo="

# Have this option to stop travis-ci building twice. Currently we have travis set to build both
# PR's and pushes. However this means when we push to a PR we have to wait for Travis to finish
# 2 builds. If we unticked 'pushes' when the PR was finally merged that would not be built. The
# brute force approach would be to untick build PR's and just build all pushes. We instead have
# gone with the approach outlined here http://stackoverflow.com/a/31882307
branches:
  only:
    - master
    - develop
