# Store sensitive data/credentials in a personal/local .env file
# which is not stored in source control.
# See the .env.example file
#
default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: <%= ENV["DB_POOL"] || 5 %>
  host: <%= Rails.application.secrets.pg_host || 'localhost' %>
  port: <%= Rails.application.secrets.pg_port || 5432 %>
  database: <%= Rails.application.secrets.pg_database || 'flood_risk' %>
  username: <%= Rails.application.secrets.pg_username || 'vagrant' %>
  password: <%= Rails.application.secrets.pg_password || 'vagrant' %>


development:
  <<: *default
  database: <%= ENV['PG_DEV_DATABASE'] || 'flood_risk_dev' %>

test:
  <<: *default
  database: <%= ENV['PG_TEST_DATABASE'] || 'flood_risk_test' %>

local_production:
  <<: *default
  database: <%= ENV['PG_PROD_DATABASE'] || 'flood_risk_prod' %>

production:
  <<: *default

