Rails.application.routes.draw do
  mount FloodRiskEngine::Engine => "/"

  if(Rails.env.development? && ENV['ADD_STATE_JUMPER_TOOLBAR'] == 'true')
    # state is optional - without it will use state of the enrollment generated by the factory
    get '/state_jumper/:factory/(:state)', :to => 'state_jumper#build_and_display', :as => :build_and_display
  end

  # Root currently defined as a Static page  - defined in config/initializers/high_voltage.rb
  # This is a Temporary Measure for show and tell etc - The real home page will be hosted on gov uk
  # and eventually point to our real root
  #
  # root to: "flood_risk_engine/enrollments#new"
end
