Rails.application.routes.draw do

  patch '/enrollments/update/:state', :to => 'enrollments#update', :as => :update_enrollment

  if(Rails.env.development? && ENV['ADD_STATE_JUMPER_TOOLBAR'] == 'true')
    # state is optional - without it will use state of the enrollment generated by the factory
    get '/state_jumper/:factory/(:state)', :to => 'state_jumper#build_and_display', :as => :build_and_display
  end

  devise_for :users, class_name: 'DigitalServicesCore::User'

  mount DigitalServicesCore::Engine => "/dsc"

  get '/dsc/enrollments/:state/:id', :to => 'digital_services_core/enrollments#update'
  get '/dsc/enrollments/:id', :to => 'digital_services_core/enrollments#update'

  root 'digital_services_core/enrollments#new'

end
