Rails.application.routes.draw do
  mount FloodRiskEngine::Engine => "/"

  if(Rails.env.development? && ENV['ADD_STATE_JUMPER_TOOLBAR'] == 'true')
    # state is optional - without it will use state of the enrollment generated by the factory
    get '/state_jumper/:factory/(:state)', :to => 'state_jumper#build_and_display', :as => :build_and_display
  end

  # Root currently defined as a static page - see config/initializers/high_voltage.rb
  # If that page is ever moved to the engine, root will need to change to eg
  # root to: "flood_risk_engine/enrollments#new"
end
