# Be sure to restart your server when you modify this file.

defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  airbrake_host: <%= ENV['AIRBRAKE_HOST'] %>
  airbrake_project_key: <%= ENV['AIRBRAKE_FO_PROJECT_KEY'] %>
  pg_host: <%= ENV['PG_HOST'] %>
  pg_port: <%= ENV['PG_PORT'] %>
  pg_database: <%= ENV['PG_DATABASE'] %>
  pg_username: <%= ENV['PG_USERNAME'] %>
  pg_password: <%= ENV['PG_PASSWORD'] %>
  address_facade_server: <%= ENV['ADDRESS_FACADE_SERVER'] %>
  address_facade_port: <%= ENV['ADDRESS_FACADE_PORT'] %>
  address_facade_client_id: <%= ENV['ADDRESS_FACADE_CLIENT_ID'] %>
  address_facade_key: <%= ENV['ADDRESS_FACADE_KEY'] %>
  address_facade_timeout:  <%= ENV['ADDRESS_FACADE_TIMEOUT'] || '10' %>

development:
  <<: *defaults
  secret_key_base: 85486f9ff6e1e5bd91b6fb0c173ce5d16377f278e8583d5c559ee35ee32d9d824b3e78541eca195c1b888b32570bb08ee8ca5fa1a9a9d9456782331647582d9b

test:
  <<: *defaults
  secret_key_base: ad2262fa281072733bf236a89a99439b8c01a7eaf16f570a68fc4bcbbbcb5722fed2d1e567d3180fb1517dd5928e8b2870b0b19f6da44a7fa61feeb4283b9950

local_production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '3a36ae2eccb7763b131a2ea0aa1a33040e670805af9e627f254b6e711efa8fc3f1a436023e707ebb3ad6dc76de23fa97c0ab826d1757ac31c374db05654b421d' %>

production: &production
  <<: *defaults
